learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#TEMPLATE TAGGING
app_name = 'basicapp'

urlpatterns= [
    url(r'^relative$',views.relative,name='relative'),
    url(r'^other$',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from basicapp import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)


def other(request):
    return render(request,'basicapp/other.html')


def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a  class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a  class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a  class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
  {% extends "basicapp/base.html" %}
    {% block body_block %}
      <h1>Welcome to index</h1>
      <h2>This is index page</h2>
      <h1>{{ text|upper  }}</h1>
      <h1>{{ text|cut:'world' }}</h1>
      <h1>{{ number|add:"90" }}</h1>

    {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
        <h1>Welcome to other</h1>
        <h2>This is an example of template inheritance</h2>
  {% endblock %}      













<!--<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to other</h1>
  </body>
</html>-->

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <!-- app_name = 'basicapp' wala name likhna hai -->
    <a href="{% url 'basicapp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index</a>
  </body>
</html>